### PR TITLE
 Implement 'preserveState' functionality

### LINKED ISSUE #22: Implement "preserveState" functionality
I've just added an option to preserve local state to Inertia core, which you can see here: https://github.com/inertiajs/inertia/pull/33

However, this must actually be implemented with the adapters themselves. I've already done this in the Vue adapter, which you can see here: https://github.com/inertiajs/inertia-vue/pull/37

The functionality is quite simple: If `preserveState` is set to true, continue using the existing page key, otherwise generate a new key to force a page component rerender. I am simply using `Date.now()` as that key.

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
This corresponds with the new "preserveState" functionality in Inertia core: inertiajs/inertia#33

Closes #22

### CODE REVIEW

**Comment by reinink** [comment]
So I updated the `updatePage()` callback signature:

```js
this.updatePage(component, page.props, { preserveState })
```

Basically just putting the options in an object, just in case we add more in the future.

Note the corresponding Vue adapter change [here](https://github.com/inertiajs/inertia-vue/pull/37/commits/09aa942dbca37cf65045519e8a45df39fac2f0ec).

**Comment by reinink** [comment]
We'll also need to update the link to include this as an option, and also update the docs. You can find examples of all this [here](https://github.com/inertiajs/inertia-vue/pull/37/files).

**Comment by sebastiandedeyne** [comment]
Looks good to me. What do you think @MichaelDeBoey, can this be merged?

**Comment by MichaelDeBoey** [comment]
Needed to add typings, but can be merged now

**Comment by sebastiandedeyne** [comment]
Thanks!

**Comment by MichaelDeBoey** [comment]
Always a pleasure to help 🙂

**Pull request merged**
