### PR TITLE
Create a dist version

### PR DESCRIPTION
**Pull request by sebastiandedeyne**
See inertiajs/inertia#58

Also moved `inertia` to peerDependencies.

### CODE REVIEW

**Comment by reinink** [comment]
Dig it Sebastian!

So, at this point, if you needed Inertia directly, you'd simply do this?

```js
// Before:
import { Inertia } from 'inertia-react'

// After:
import Inertia from 'inertia'
```

This makes me also wonder if we should update our docs to say `InertiaReact` for the app:

```js
import InertiaReact from 'inertia-react'
import React from 'react'
import { render } from 'react-dom'

const app = document.getElementById('app')

render(
  <InertiaReact
    initialPage={JSON.parse(app.dataset.page)}
    resolveComponent={name => import(`@/Pages/${name}`).then(module => module.default)}
  />,
  app
)
```

Thoughts?

**Comment by sebastiandedeyne** [comment]
Jep, could also call it somthing like `App` but that might clash with what users have.

**Comment by fnandogp** [comment]
> This makes me also wonder if we should update our docs to say `InertiaReact` for the app:
> 
> ```js
> import InertiaReact from 'inertia-react'
> import React from 'react'
> import { render } from 'react-dom'
> 
> const app = document.getElementById('app')
> 
> render(
>   <InertiaReact
>     initialPage={JSON.parse(app.dataset.page)}
>     resolveComponent={name => import(`@/Pages/${name}`).then(module => module.default)}
>   />,
>   app
> )
> ```
> 
> Thoughts?

I had trouble to understand that both things are different. I was trying to do something like `Inertia.post( ... )` and had to dig into the code to understand why isn't working.

So, for me, I think that is a good idea.

**Comment by reinink** [comment]
Yeah, if we go with all named exports it could even be something like this:

```js
import { InertiaApp, InertiaLink } from 'inertia-react'
```

**Pull request merged**
