### PR TITLE
[DRAFT] Update to new Inertia.init() signature

### LINKED ISSUE #21: Update to new Inertia.init() signature
The `Inertia.init()` signature has changed, and needs to be updated in the React adapter. As you can see in the [Vue adapter](https://github.com/inertiajs/inertia-vue/blob/master/src/app.js#L31-L38), it now takes one object argument:

```js
Inertia.init({
  initialPage: this.initialPage, // the inital page prop
  resolveComponent: this.resolveComponent, // the resolve component prop
  updatePage: (component, props) => {}, // callback to update the page
})
```

Basically this update just splits resolving the component apart from actually updating the page, so that we can do a check in between to verify that the page still needs to be update. This is all part of a fix that resolves an annoying race condition when using code splitting, which you can learn more about here: https://github.com/inertiajs/inertia/pull/25

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
This corresponds to the improvements made to Inertia core around visit cancellation (inertiajs/inertia#32).

Closes #21

### CODE REVIEW

**Comment by sebastiandedeyne** [comment]
Thanks!

**Comment by MichaelDeBoey** [comment]
This was still a draft, but no prob 😛😉

**Comment by sebastiandedeyne** [comment]
It looked done to me :D Was there something you still wanted to change?

**Comment by MichaelDeBoey** [comment]
Not really, but because of the possible merge conflict with the `transformProps`, I made this one a draft until that one was merged.
Was planning on rebasing this one then, but will made a PR (#26) to fix the merge conflicts 🙂

**Pull request merged**
