### PR TITLE
Add type-checking of component props

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Just like we do in inertiajs/inertia-vue (see [`app.js`](https://github.com/inertiajs/inertia-vue/blob/master/src/app.js#L8-L9) or [`link.js`](https://github.com/inertiajs/inertia-vue/blob/master/src/link.js#L6-L18)), I've added type checking of the component props.

I've also made the props without a default value required.

### CODE REVIEW

**Comment by sebastiandedeyne** [comment]
I don't want to add a runtime dependency for type checking, if people want type checking they should use TypeScript or Flow. I don't think it's recommended to use `prop-types` anymore since other solutions are vastly superior.

I'm planning on adding and `index.d.ts` with TypeScript types so we have editor autocompletion and type safety when consuming the library (I already have a partial version ready in my own projects).

I'd wouldn't mind writing this library entirely in TypeScript though, but I don't know what @reinink's stance is about that 😬

**Comment by MichaelDeBoey** [comment]
I've added this one, since Vue has this natively.

React did too, but it was extracted to the `prop-types` package

**Comment by sebastiandedeyne** [comment]
If it was still in core, I'd add the prop types. But I don't think it's worth increasing the bundle size for this.

**Comment by MichaelDeBoey** [comment]
Happy to send a PR for the Typescript types instead tho 🙂

**Comment by MichaelDeBoey** [comment]
@sebastiandedeyne Have added a draft for it in #15

**Pull request closed without merging**
